- name: Setup Frontend
  hosts: all
  become: true
  tasks:
    - name: Install nginx server
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Remove default directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Remove default directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download & extract frontend content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Setup reverse proxy
      ansible.builtin.copy:
        src: frontend.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Start nginx service
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: restarted








#
#echo -e "${color}Setup reverse proxy${nocolor}"
#cp /home/centos/roboshop4-shell/frontend.conf /etc/nginx/default.d/roboshop.conf    &>>${logfile}
#func_StatCheck $?
#
#echo -e "${color}Start Nginx${nocolor}"
#systemctl enable nginx    &>>${logfile}
#systemctl restart nginx   &>>${logfile}
#func_StatCheck $?