- name: Enable nodejs18
  ansible.builtin.dnf:
    name: nodejs=18
    state: present

- name: Install nginx server
  ansible.builtin.dnf:
    name: nodejs
    state: installed






#echo -e "${color}Enable 18 version ${nocolor}"
#dnf module disable nodejs -y    &>>${logfile}
#dnf module enable nodejs:18 -y    &>>${logfile}
#func_StatCheck $?
#
#echo -e "${color}Install nodejs${nocolor}"
#dnf install nodejs -y   &>>${logfile}
#func_StatCheck $?
#
#func_AppPresetup
#
#echo -e "${color}Download App Dependencies${nocolor}"
#npm install   &>>${logfile}
#func_StatCheck $?
#
#func_systemd