- name: Setup erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/{{ item }} | bash
  loop:
    - erlang/script.rpm.sh
    - script.rpm.sh

- name: Install rabbitmq
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Start rabbitmq service
  ansible.builtin.systemd:
    name: rabbitmq-server
    enabled: yes
    state: restarted

- name: Create app user and fix permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present