- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Load App presetup
  ansible.builtin.include_tasks:
    file: app-presetup.yml

- name: Download App Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app

- name: Load mysql
  ansible.builtin.include_tasks:
    file: mysql.yml

- name: Load systemd
  ansible.builtin.include_tasks:
    file: systemd.yml