- name: Configuring NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Include App-presetup file
  ansible.builtin.include_tasks:
    file: app-presetup.yml

- name: Install nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Load mongo schema
  - ansible.builtin.include_tasks:
      file: mongo-schema_setup.yml
    when: load_schema

- name: Setup systemd
  ansible.builtin.include_tasks:
    file: systemd.yml